### PR TITLE
Add REST Catalog and generate some test data

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Comment by Fokko** [comment]
It looks like the CI is failing on main? https://github.com/duckdb/duckdb_iceberg/actions/runs/6800435295/job/18523077842?pr=27

**Comment by samansmink** [comment]
Hey @Fokko thanks for the PR! Yea this is a known issue, check out https://github.com/duckdb/duckdb_iceberg/pull/28, this should fix it

**Comment by Fokko** [comment]
@samansmink ah nice one, thanks!

**Comment by samansmink** [comment]
Hey @Fokko! I think CI is failing because docker compose is not available in the manylinux image. 
However for these tests I think it suffices to have this run only on the ubuntu:18.04 job.
The arm job can be stripped as well because as it is cross compiled, we can not test with it anyway

So could you strip both the linux_arm64 and the linux_amd64_gcc4 from the REST.yml?

**Comment by Fokko** [comment]
Hey @samansmink thanks for pinging me. Let me check right away!

**Comment by Fokko** [comment]
@samansmink It should pass now. It was a bit of a hassle with the docker-in-docker problem, but let me know what you think!

**Comment by samansmink** [comment]
@Fokko Thanks a lot for all the work on this. Having a proper iceberg setup to test against is super useful! I've started CI for the PR

After this gets merged I'll look into using this for more of the tests and implementing the REST Catalog against this

**Comment by Fokko** [comment]
Hey @samansmink Cool stuff

The spec can be found here: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml

Personally, I like to check the Python objects [here](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.py) to see what the requests/responses are. I think it is easier to read than the yaml. Let me know if you need any help!

**Comment by samansmink** [comment]
LGTM, thanks again!

**Pull request merged**
