### PR TITLE
Add predicate pushdown

### PR DESCRIPTION
**Pull request by mike-luabase**

### CODE REVIEW

**Comment by mike-luabase** [comment]
@samansmink this PR adds predicate pushdown for Iceberg. It does not currently support CTEs.

closes https://github.com/duckdb/duckdb_iceberg/issues/2 although more work is needed to support multiple iceberg scans (e.g. thru a CTE).

**Comment by samansmink** [comment]
Hey @mike-luabase! Thanks for the PR! 

Please be aware that we are planning to migrate the Iceberg scan from the current bind_replace to use the MultiFileReader interface, see [this PR](https://github.com/duckdb/duckdb/pull/11806).

However, since i can't give an expected timeline for that at this moment, I think this can be a good intermediate solution to have predicate pushdown working in the meantime. Just be aware that the code might get replaced at some point.

**Comment by samansmink** [comment]
@mike-luabase I've updated the iceberg extension repo to 1.1.1. Merging with master should build your changes against latest stable duckdb and latest CI. 

Would you also mind adding a description describing how you tackled the (pretty complex!) task of supporting filter pushdown? This makes it easier for future maintainers to understand how this works.

**Comment by catkins** [comment]
For anyone following along, this was moved to 👉  https://github.com/duckdb/duckdb-iceberg/pull/78

**Comment by psirenny** [comment]
> For anyone following along, this was moved to 👉  https://github.com/duckdb/duckdb-iceberg/pull/78

I don't know, it looks like that pull request has stalled. The author hasn't responded to feedback which, is fair given how long it took to receive it.

**Comment by catkins** [comment]
Yeah, thats fair. I was mostly making sure there was a link from #2 -> #72 -> #78 for anyone curious on predicate pushdown.

I'm mostly just excited to see what @Mytherin and the DuckDB Labs team bring in the world of Iceberg and lakehouses this year. It was mentioned as a priority at Duckcon the other week!

**Comment by mike-luabase** [comment]
also worth linking: https://github.com/duckdb/duckdb-iceberg/pull/101

**Pull request closed without merging**
